version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      # Persist bot data
      - ./data:/app/data
      # Mount logs directory
      - ./logs:/app/logs
    networks:
      - telegram-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  telegram-network:
    driver: bridge

volumes:
  telegram-data:
    driver: local 